const products = [
  {
    id: 1,
    name: "Simple Burger",
    description: "Bun, meat, and lettuce.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerSencilla.webp",
    price: 400,
    stock: 10,
    feature: true,
  },
  {
    id: 2,
    name: "Double Burger",
    description: "Bun, meat x2, tomato, and lettuce.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerDobleEspecial.webp",
    price: 600,
    stock: 10,
    feature: true,
  },
  {
    id: 3,
    name: "Chicken Burger",
    description: "Chicken, lettuce, and tomato.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerPollo.webp",
    price: 700,
    stock: 10,
    feature: false,
  },
  {
    id: 4,
    name: "Random Burger",
    description: "Meat, cucumber, and tomato.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerPepino.webp",
    price: 800,
    stock: 10,
    feature: false,
  },
  {
    id: 5,
    name: "Egg Burger",
    description: "Like the one from McDonald's but better.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/burgerhuevo.webp",
    price: 700,
    stock: 10,
    feature: true,
  },
  {
    id: 6,
    name: "Veggie Burger",
    description: "Vegetarian burger.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerVeggie.webp",
    price: 550,
    stock: 10,
    feature: false,
  },
  {
    id: 7,
    name: "Fries with Bacon",
    description: "French fries with bacon.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/PapasBacon.webp",
    price: 250,
    stock: 10,
    feature: true,
  },
  {
    id: 8,
    name: "Regular Fries",
    description: "Regular French fries.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/PapasComunes.webp",
    price: 300,
    stock: 10,
    feature: false,
  },
  {
    id: 9,
    name: "Rustic Fries",
    description: "Rustic French fries.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/PapasRusticas.webp",
    price: 350,
    stock: 10,
    feature: false,
  },
  {
    id: 10,
    name: "Special Fries",
    description: "Special French fries.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/PapasEspeciales.webp",
    price: 300,
    stock: 10,
    feature: false,
  },
  {
    id: 11,
    name: "Salad",
    description: "Fresh salad.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Ensalada.webp",
    price: 400,
    stock: 10,
    feature: false,
  },
  {
    id: 12,
    name: "Double Cola",
    description: "Contains 15 kilos of sugar.",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Coca.webp",
    price: 70,
    stock: 10,
    feature: false,
  },
  {
    id: 13,
    name: "Zup",
    description: "Contains 7up and Sprite but it's Zup.",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Zup.webp",
    price: 30,
    stock: 10,
    feature: true,
  },
  {
    id: 14,
    name: "Moñster",
    description: "Energy drink.",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Monster.webp",
    price: 45,
    stock: 10,
    feature: false,
  },
  {
    id: 15,
    name: "Water",
    description: "This is the water Cristiano Ronaldo drinks.",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Agua.webp",
    price: 70,
    stock: 10,
    feature: false,
  },
  {
    id: 16,
    name: "Rud Bell",
    description: "Energy drink that doesn't give you wings.",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/RedBull.webp",
    price: 41,
    stock: 10,
    feature: false,
  },
  {
    id: 17,
    name: "Nix",
    description: "Recommended for the end of the month.",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Nix.webp",
    price: 25,
    stock: 10,
    feature: false,
  },
  {
    id: 18,
    name: "Seba Ice Cream",
    description: "It's a cone.",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/HeladoCono.webp",
    price: 350,
    stock: 10,
    feature: true,
  },
  {
    id: 19,
    name: "Large Ice Cream",
    description: "Large ice cream.",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/HeladoGrande.webp",
    price: 250,
    stock: 10,
    feature: false,
  },
  {
    id: 20,
    name: "Flan",
    description: "Flan with caramel.",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Flan.webp",
    price: 200,
    stock: 10,
    feature: false,
  },
  {
    id: 21,
    name: "Strawberry Milkshake",
    description: "Strawberry milkshake.",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/MilkshakeFrutilla.webp",
    price: 350,
    stock: 10,
    feature: false,
  },
  {
    id: 22,
    name: "Vanilla Milkshake",
    description: "Vanilla milkshake.",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/MilkshakeVainilla.webp",
    price: 345,
    stock: 10,
    feature: false,
  },
  {
    id: 23,
    name: "Chocolate Milkshake",
    description: "Chocolate milkshake.",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/MilkshakeChocolate.webp",
    price: 250,
    stock: 10,
    feature: false,
  },
  {
    id: 24,
    name: "Espresso Coffee",
    description: "It's espresso.",
    categoryId: 5,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/CoffeeExpresso.webp",
    price: 145,
    stock: 10,
    feature: false,
  },
  {
    id: 25,
    name: "Cappuccino",
    description: "With milk.",
    categoryId: 5,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Cappuchino.webp",
    price: 165,
    stock: 10,
    feature: false,
  },
  {
    id: 26,
    name: "Decaffeinated",
    description: "No coffee.",
    categoryId: 5,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Descafeinado.webp",
    price: 160,
    stock: 10,
    feature: false,
  },
  {
    id: 27,
    name: "Double Espresso",
    description: "It's double espresso.",
    categoryId: 5,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/ExpressoDoble.webp",
    price: 150,
    stock: 10,
    feature: false,
  },
];

const { Product } = require("../models");

async function productsSeeder() {
  try {
    await Product.bulkCreate(products);
    console.log("the seeders of products are running");
  } catch (error) {
    console.error("Error al ejecutar el seeder de productos:", error);
  }
}

module.exports = productsSeeder;
