const products = [
  {
    name: "Burger Sencilla",
    description: "Pan, carne y lechuga.",
    categoryId: 1,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/BurgerSencilla.webp",
    price: 150,
    stock: 10,
    feature: true,
  },
  {
    name: "Burger Doble",
    description: "Pan, carne x2, tomate y lechuga.",
    categoryId: 1,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/BurgerDobleEspecial.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Burger Pollo",
    description: "Pollo, lechuga y tomate.",
    categoryId: 1,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/BurgerPollo.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Burger Random",
    description: "Carne, pepino, y tomate.",
    categoryId: 1,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/BurgerPepino.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Egg Burger",
    description: "Como la de Mcdonalds pero mejor.",
    categoryId: 1,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/burgerhuevo.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Burger Veggie",
    description: "Hamburguesa vegetariana.",
    categoryId: 1,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/BurgerVeggie.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Papas con Bacon",
    description: "Papas fritas con bacon.",
    categoryId: 2,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/PapasBacon.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Papas Comunes",
    description: "Papas fritas comunes.",
    categoryId: 2,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/PapasComunes.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Papas Rusticas",
    description: "Papas fritas rústicas.",
    categoryId: 2,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/PapasRusticas.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Papas Especiales",
    description: "Papas fritas especiales.",
    categoryId: 2,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/PapasEspeciales.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Ensalada",
    description: "Ensalada fresca.",
    categoryId: 2,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/Ensalada.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },{
    name: "Ensalada",
    description: "Ensalada fresca.",
    categoryId: 3,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/Ensalada.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Helado Seba",
    description: "Es un cono",
    categoryId: 4,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/HeladoCono.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Helado Grande",
    description: "Helado grande.",
    categoryId: 4,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/HeladoGrande.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Flan",
    description: "Flan con caramelo.",
    categoryId: 4,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/Flan.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "MilkShake Frutilla",
    description: "Milkshake de frutilla.",
    categoryId: 4,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/MilkshakeFrutilla.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "MilkShake Vainilla",
    description: "Milkshake de vainilla.",
    categoryId: 4,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/MilkshakeVainilla.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "MilkShake Chocolate",
    description: "Milkshake de chocolate.",
    categoryId: 4,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/MilkshakeChocolate.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },{
    name: "Coffee",
    description: "Café?",
    categoryId: 5,
    photo: "https://goodburger.s3.us-east-2.amazonaws.com/Ensalada.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
];

const { Product } = require("../models");

async function productsSeeder() {
  try {
    await Product.bulkCreate(products);
    console.log("the seeders of products are running");
  } catch (error) {
    console.error("Error al ejecutar el seeder de productos:", error);
  }
}

module.exports = productsSeeder;
