const products = [
  {
    name: "Burger Sencilla",
    description: "Pan, carne y lechuga.",
    categoryId: 1,
    photo:
      "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerSencilla.webp",
    price: 150,
    stock: 10,
    feature: true,
  },
  {
    name: "Burger Doble",
    description: "Pan, carne x2, tomate y lechuga.",
    categoryId: 1,
    photo:
      "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerDobleEspecial.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Burger Pollo",
    description: "Pollo, lechuga y tomate.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerPollo.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Burger Random",
    description: "Carne, pepino, y tomate.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerPepino.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Egg Burger",
    description: "Como la de Mcdonalds pero mejor.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/burgerhuevo.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Burger Veggie",
    description: "Hamburguesa vegetariana.",
    categoryId: 1,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/BurgerVeggie.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Papas con Bacon",
    description: "Papas fritas con bacon.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/PapasBacon.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Papas Comunes",
    description: "Papas fritas comunes.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/PapasComunes.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Papas Rusticas",
    description: "Papas fritas rústicas.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/PapasRusticas.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Papas Especiales",
    description: "Papas fritas especiales.",
    categoryId: 2,
    photo:
      "https://goodburgeruy.s3.sa-east-1.amazonaws.com/PapasEspeciales.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Ensalada",
    description: "Ensalada fresca.",
    categoryId: 2,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Ensalada.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Cola Loca",
    description: "Como la de tu jermu.",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Coca.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Zup",
    description: "NO es 7up",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Zup.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Moñster",
    description: "Lo mismo pero mas barato.",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Monster.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Agua",
    description: "Como la que toma el bicho. SIUUUUU",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Agua.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Rud Bell",
    description: "No te da alas",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/RedBull.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Nix",
    description: "Es un elisir",
    categoryId: 3,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Nix.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Helado Seba",
    description: "Es un cono",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/HeladoCono.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Helado Grande",
    description: "Helado grande.",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/HeladoGrande.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Flan",
    description: "Flan con caramelo.",
    categoryId: 4,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Flan.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "MilkShake Frutilla",
    description: "Milkshake de frutilla.",
    categoryId: 4,
    photo:
      "https://goodburgeruy.s3.sa-east-1.amazonaws.com/MilkshakeFrutilla.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "MilkShake Vainilla",
    description: "Milkshake de vainilla.",
    categoryId: 4,
    photo:
      "https://goodburgeruy.s3.sa-east-1.amazonaws.com/MilkshakeVainilla.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "MilkShake Chocolate",
    description: "Milkshake de chocolate.",
    categoryId: 4,
    photo:
      "https://goodburgeruy.s3.sa-east-1.amazonaws.com/MilkshakeChocolate.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
  {
    name: "Café Expresso",
    description: "El azucar no viene incluida.",
    categoryId: 5,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/CoffeeExpresso.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },{
    name: "Capuchino",
    description: "Con leche, como te gusta.",
    categoryId: 5,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Cappuchino.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },{
    name: "Descafeinado",
    description: "Tengo que decirlo?",
    categoryId: 5,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/Descafeinado.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },{
    name: "Expresso Doble",
    description: "Fuerte como patada de Javi Mendez",
    categoryId: 5,
    photo: "https://goodburgeruy.s3.sa-east-1.amazonaws.com/ExpressoDoble.webp",
    price: 1000,
    stock: 10,
    feature: true,
  },
];

const { Product } = require("../models");

async function productsSeeder() {
  try {
    await Product.bulkCreate(products);
    console.log("the seeders of products are running");
  } catch (error) {
    console.error("Error al ejecutar el seeder de productos:", error);
  }
}

module.exports = productsSeeder;
